version: '3'

volumes:
  local_postgres_data: {}

services:
  db:
    image: postgres:14
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

  web:
    build: .
    image: julo_mini_wallet_web
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
    - ./.envs/.django
    - ./.envs/.postgres
    depends_on:
      - db
  